# /*DIALLO ALPHA ET        VERSION DU 24/05/2005*/
ville: shop.o 
	gcc   -g  -o shop shop.o -lpthread

shop.o: shop.c shop.h
	gcc  -g  -c shop.c -lpthread

clean:
	rm -f *.o *.c~ *.h~ makefile~ ville *.dat~

